//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Launcher.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mapzoomdata {
            get {
                object obj = ResourceManager.GetObject("mapzoomdata", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///
        ///&lt;CMenuArray v=&quot;5.0&quot;&gt;
        ///&lt;!-- kng is a meow lol --&gt;
        ///	&lt;GeneralData v=&quot;2.4&quot;&gt;
        ///
        ///		&lt;MovieSettings&gt;
        ///			&lt;Item key=&quot;MinimapBG&quot;&gt;
        ///				&lt;vPos 	x=&quot;0.162&quot; y=&quot;0.222&quot;/&gt;
        ///				&lt;vSize 	x=&quot;0.6785&quot; y=&quot;0.5975&quot;/&gt;
        ///			&lt;/Item&gt;
        ///			
        ///			&lt;Item key=&quot;GalleryBG&quot;&gt;
        ///				&lt;vPos 	  x=&quot;0.615&quot;  y=&quot;0.222&quot;/&gt;
        ///				&lt;vSize 	  x=&quot;0.225&quot;     y=&quot;0.5975&quot;/&gt;
        ///			&lt;/Item&gt;
        ///			
        ///			&lt;Item key=&quot;CoronaMapBG&quot;&gt;
        ///				&lt;vPos 	  x=&quot;0.615&quot;  y=&quot;0.222&quot;/&gt;
        ///				&lt;vSize 	  x=&quot;0.225&quot;     y=&quot;0.5975&quot;/&gt;
        ///			&lt;/Item&gt;
        ///			
        ///			&lt;Item k [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pausemenu {
            get {
                return ResourceManager.GetString("pausemenu", resourceCulture);
            }
        }
    }
}
