// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("2020.6.15.2125")]
[assembly: AssemblyFileVersion("2020.6.15.2125")]