<?php

require 'ayarlar.php';

?>{
	"version": "<?=$exe_version?>", 
	"update_file": "<?=$update_file?>",
	"server": "<?=$fivem_server?>", 
	"discord": "<?=$discord?>", 
	"teamspeak3": "<?=$teamspeak3?>", 
	"server_code": "<?=$fivem_code?>",
	"cheats": [
		"2take1free",
		"cheat engine", "cheatengine",
		"dex menu", "dexmenu",
		"eulen",
		"fx premium", "fxpremium",
		"gh injector", "ghinjector",
		"ham mafia", "hammafia",
		"injection", "injector",
		"kaynak İzleyicisi", "kaynak izleyicisi", "kaynakİzleyicisi", "kaynakizleyicisi",
		"lynx",
		"machine therapist", "machinetherapist", "machine_therapist",
		"premium",
		"process hacker", "processhacker",
		"renamenu",
		"roblox player", "robloxplayer",
		"root",
		"taskmgr", "task manager", "taskmanager",
		"memoscope",
		"proc dump", "procdump",
		"process explorer", "processexplorer",
		"process monitor", "processmonitor",
		"debugger",
		"ollydbg",
		"reclassex", 
		"x64dbg", "x32dbg",
		"ida pro", "idapro", "ida", "ida64", "ida32",
		"ghidra", 
		"de4dot", 
		"dotpeek64", "dotpeek32", 
		"fiddler", 
		"dnspy",
		"desudo",
		"brutan",
		"player crash", "playercrash",
		"34byte",
		"alphav",
		"vjuton",
		"soviet bear", "sovietbear",
		"marvin menu", "marvinmenu"
	]
}